name: FF Data Update

on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 1 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install espn-api

    - name: Run update script
      env:
        LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
        ESPN_S2: ${{ secrets.ESPN_S2 }}
        SWID: ${{ secrets.SWID }}
      run: FF-pros.py

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add fantasy_football_data.json
        git diff --staged --quiet || (git commit -m "Update fantasy football data")
        git fetch origin main
        git checkout main
        git reset --hard origin/main
        git cherry-pick ORIG_HEAD
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
