name: Update Fantasy Football Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  push:
    paths:
      - 'fantasy_football_data.json'
      - 'process_fantasy_data.py'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Add any other dependencies your script might need

    - name: Debug - Print current directory and list files
      run: |
        pwd
        ls -R

    - name: Run data processing script
      run: |
        if [ -f "process_fantasy_data.py" ]; then
          python process_fantasy_data.py
        else
          echo "Error: process_fantasy_data.py not found"
          exit 1
        fi

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add processed_fantasy_football_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update processed fantasy football data" && git push)
