name: Update Fantasy Football Data

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install espn-api

    - name: Run update script
      env:
        LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
        ESPN_S2: ${{ secrets.ESPN_S2 }}
        SWID: ${{ secrets.SWID }}
      run: python /blob/9f840a4bf609d5d753de49eb1b31ea1c31bd2b3c/fantasy-football-data-export.py
      

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add fantasy_football_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update fantasy football data" && git push)
