name: Update Fantasy Football Data

on:
  schedule:
    # This runs the script every day at 1:00 UTC
    # Adjust the cron schedule as needed
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install espn-api

    - name: Run update script
      run: python ffstats/blob/main/fantasy_football_data_export.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add fantasy_football_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update fantasy football data" && git push)
